[package]
name = "zkevm_test_harness"
version = "1.5.0"
edition = "2021"
authors = ["Alex Vlasov <alex.m.vlasov@gmail.com>", "Konstantin Panarin <kp@matterlabs.dev>"]

resolver = "2"

# [[bin]]
# name = "circuit_limit_estimator"
# path = "src/circuit_limit_estimator/main.rs"

# [[bin]]
# name = "circuit_synthesis_performance_test"
# path = "src/circuit_synthesis_performance_test/main.rs"

[[bin]]
name = "geometry_config_generator"
path = "src/geometry_config_generator/main.rs"

[dependencies]
circuit_definitions = {path = "./circuit_definitions"}
circuit_sequencer_api = {path = "./circuit_sequencer_api"}
kzg = {path = "./kzg"}

zkevm-assembly = {git = "https://github.com/matter-labs/era-zkEVM-assembly.git", branch = "v1.5.0"}

rand = "0.4"
rayon = "*"
derivative = "*"
hex = "*"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
crossbeam = "0.8"
tracing = { version= "0.1.26" }
bincode = "*"
test-log = "*"
env_logger = "*"
smallvec = "*"
structopt = "0.3.26"
codegen = "0.2.0"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["blocking"] }
curl = "0.4"
walkdir = "2.4"
regex = { version = "1.10.4", features = ["pattern"] }

[dev-dependencies]
rand = "0.4"

[profile.release]
debug = false
lto = false

[profile.bench]
debug = false

[features]
verbose_circuits = ["circuit_definitions/verbose_circuits", "circuit_sequencer_api/verbose_circuits"]